---
# MegaLinter GitHub Actions workflow for sast scans
name: MegaLinter sast

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  megalinter-sast:
    name: MegaLinter sast Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter sast Scan
        id: ml
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Dynamically enable linters based on detected languages: C++, Shell, CMake, Dockerfile, Python, 
          ENABLE_LINTERS: >-
            REPOSITORY_SEMGREP,

          # Tool-specific configurations
          REPOSITORY_SEMGREP_ARGUMENTS: "--config=p/security-audit"
          REPOSITORY_SEMGREP_RULESETS_TYPE: security

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

      # Create pull request with fixes if applicable
      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v4
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES == 'all' || env.APPLY_FIXES == 'true')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply sast fixes"
          title: "[MegaLinter] Apply sast fixes"
          labels: bot
