---
# MegaLinter GitHub Actions workflow for static_analysis scans
name: MegaLinter static_analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  megalinter-static_analysis:
    name: MegaLinter static_analysis Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter static_analysis Scan
        id: ml
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Dynamically enable linters based on detected languages: C++, Shell, CMake, Dockerfile, Python, 
          ENABLE_LINTERS: >-
            CPP_CPPCHECK,
            PYTHON_BANDIT,

          # Tool-specific configurations
          CPP_CPPCHECK_ARGUMENTS: "--enable=all --inconclusive --suppress=missingIncludeSystem"
          PYTHON_BANDIT_ARGUMENTS: "-ll -ii"

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

      # Create pull request with fixes if applicable
      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v4
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES == 'all' || env.APPLY_FIXES == 'true')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply static_analysis fixes"
          title: "[MegaLinter] Apply static_analysis fixes"
          labels: bot
